const fs = require('fs');

const dataContent = `/* ==========================================================================
   GIBS CONTENT LAYER — Single Source of Truth for Institutional Data.
   ========================================================================== */

import type {
  InstitutionInfo,
  ContactInfo,
  CampusInfo,
  FacultyDesignation,
  Programme,
  GIBS_EVENT,
} from "../types/data";

export type { Programme } from "../types/data";

export const DATA_REQUIRED = "[OFFICIAL GIBS DATA REQUIRED]";

export const INSTITUTION: InstitutionInfo = {
  legalName: "Goshen International Business School Limited",
  abbreviation: "GIBS",
  cac: "RC 1178333",
  incorporationDate: "March 17, 2014",
  registrationAuthority: "Corporate Affairs Commission, Ilorin",
  slogan: "Take advantage of us, so that no one takes advantage of you",
  positioning:
    "An outfit committed to manpower development and capacity-building. Our uniqueness is in our dedication to capacity-building exercise.",
  mission:
    "Goshen International Business School (GIBS) is dedicated to empowering the future generation through acquisition and communication of management and business knowledge relevant to the development of Nigeria and the world at large. We are a world-class Business School impacting positively on the public and private sectors of the economy.",
  vision:
    "To support the development of National Manpower and Economic Development Policies for the emancipation of the people.",
  guidingPrinciples: ["Thoroughness", "Fair", "Firm", "Forthright"],
  coreValues: [
    "Integrity",
    "Diligence",
    "Excellence",
    "Professionalism",
    "Responsiveness",
    "Innovation",
    "Commitment",
  ],
  strategicFocus: [
    "Availability of required knowledge update",
    "Updating knowledge of stakeholders",
    "Bridge the gap in knowledge",
    "Introduce new developments in the society",
    "Provide platform for the support of our stakeholders",
  ],
};

export const CONTACTS: ContactInfo = {
  website: "www.gibs.com.ng",
  emails: ["gibsilorin@gmail.com", "goshenibs22@gmail.com"],
  phones: [
    "08160010401",
    "08033429427",
    "08186464474",
    "08032296041",
    "07085792767",
  ],
  postalAddress:
    "P.O. Box 63, Ilorin General Post Office, Kwara State, Nigeria",
};

export const CAMPUSES: CampusInfo[] = [
  {
    id: "ilorin-hq",
    name: "Ilorin Headquarters (Main HQ)",
    type: "Headquarters",
    address:
      "No 81, Olorunsogo Street, Off Agbabiaka Road, Upper Gaa - Akanbi, Ilorin, Kwara State, Nigeria",
    facilities: [
      "12 Lecture Rooms",
      "Library",
      "100-person capacity Hall",
      "20-Room Guest Facility",
    ],
    capacity: "300–500 participants across workshop or large formats",
    recreationalFacilities: [
      "Olympic-size Lawn Tennis court",
      "International standard Table Tennis",
      "Open space keep-fit grounds",
      "3 medium-size Halls",
      "16-seater buses",
      "6-seater mini-bus",
      "24/7 power supply",
      "Assured security",
    ],
  },
  {
    id: "abuja",
    name: "Abuja Center",
    type: "Campus",
    address:
      "Plot 194, Lugbe 1 Layout, Near Okay Centre, Direct Behind Rainoil filling station, FHA Lugbe, Airport Road, Abuja",
    facilities: [
      "2 Halls (100-person capacity each)",
      "7 Lecture Rooms",
      "2 Administrative offices",
      "2 Syndicate rooms",
      "3-Room guest facility",
      "2 standby power generating sets",
      "18 toilets",
      "Large parking lot",
    ],
    capacity: "300–500 participants across workshop or large formats",
  },
  {
    id: "ibafo",
    name: "Ibafo (Ogun State) Center",
    type: "Campus",
    address:
      "KM 36, Lagos - Ibadan Express Road, Adjacent Dap-Mude Hotel, Behind World Oil Station, Ibafo, Ogun State, Nigeria",
    facilities: [
      "1 Hall",
      "4 Lecture Rooms",
      "4 Syndicate Rooms",
    ],
    capacity: "300–500 participants across workshop or large formats",
  },
];

export const CAPACITY = {
  regularCapacity:
    "300 candidates across 6 classes of 25 participants in Workshop/Seminar formats, or up to 500 people in a single large class format per campus.",
  workshopFormat: "300 candidates across 6 classes of 25 participants per campus",
  largeClassFormat: "Up to 500 candidates per campus",
  offCampusApprovedLocations: [
    "Lagos",
    "Keffi",
    "Kaduna",
    "Owerri",
    "Port Harcourt",
    "Benin City",
  ],
  offCampusCities: [
    "Lagos",
    "Keffi",
    "Kaduna",
    "Owerri",
    "Port Harcourt",
    "Benin City",
  ],
};

export const GOVERNANCE = {
  council: "Governing Council",
  structure:
    "4 Directors under the Chairman of the Council; Management team of 20 Advisors and experts.",
};

export const FACULTY_DESIGNATIONS: FacultyDesignation[] = [
  { id: "01", title: "Chairman, Academic Board", department: "Academic Board" },
  { id: "02", title: "Advisor, Environmental Sustainability Project", department: "Environmental Projects" },
  { id: "03", title: "Advisor, Training and Manpower Development", department: "Capacity Building" },
  { id: "04", title: "Advisor, International Partnership", department: "Global Relations" },
  { id: "05", title: "Advisor, Economic Development Project", department: "Economic Research" },
  { id: "06", title: "Advisor, Legal and Regulatory Services", department: "Legal Affairs" },
  { id: "07", title: "Advisor, Curriculum Development", department: "Academic Affairs" },
  { id: "08", title: "Coordinator, Academic Activities", department: "Academic Operations" },
  { id: "09", title: "Advisor, Inter-Agencies Services", department: "Public Sector Relations" },
  { id: "10", title: "Advisor, Financial Services", department: "Finance & Strategy" },
  { id: "11", title: "Coordinator, General Services", department: "Institutional Operations" },
  { id: "12", title: "Acting Registrar and Coordinator, ICT Services", department: "Registry & Technology" },
  { id: "13", title: "Coordinator, External Relations", department: "Corporate Communications" },
  { id: "14", title: "Coordinator, Research and Development", department: "Research & Development" },
];

export const ACCREDITATIONS = [
  "CAC RC 1178333",
  "Centre for Management Development (CMD)",
  "Industrial Training Fund (ITF) Certificate of Compliance",
  "NSTIF",
];

export const INTERNATIONAL = {
  technicalPartner: "Pacific Institute of Technology, Georgia, United States of America",
  overseasHubs: [
    "Miami (USA)",
    "Houston (USA)",
    "London (UK)",
    "Dubai (UAE)",
    "Cape Town (South Africa)",
    "Durban (South Africa)",
    "Kigali (Rwanda)",
    "Netherlands",
    "Ghana",
  ],
};

export const IMAGES = {
  hero: "/images/hero-campus.jpg",
  colonnade: "/images/campus-colonnade.jpg",
  library: "/images/library-interior.jpg",
  boardroom: "/images/library-interior.jpg",
  city: "/images/hero-campus.jpg",
  lecture: "/images/library-interior.jpg",
  seminar: "/images/campus-colonnade.jpg",
  books: "/images/library-interior.jpg",
  study: "/images/library-interior.jpg",
};

export const NAV_LINKS = [
  { label: "Programmes", to: "/programmes" },
  { label: "Executive Education", to: "/executive-education" },
  { label: "Faculty & Research", to: "/faculty" },
  { label: "About GIBS", to: "/about" },
  { label: "Admissions", to: "/admissions" },
];

export const EVENTS: GIBS_EVENT[] = [];

/* ---------------- COMPLETE 135 PROGRAMMES DATASET ---------------- */

const makeProgramme = (p: Partial<Programme> & { slug: string; title: string; category: string; fee: string; feeAmount: number; currency: "NGN" | "USD" | "GBP"; target: string; schedule: string; location: string; destination: string; programmeType: "Local/Open" | "Foreign"; number?: number }): Programme => ({
  id: p.id || p.slug,
  number: p.number,
  slug: p.slug,
  title: p.title,
  category: p.category,
  programmeType: p.programmeType,
  fee: p.fee,
  fees: p.fee,
  currency: p.currency,
  feeAmount: p.feeAmount,
  target: p.target,
  schedule: p.schedule,
  location: p.location,
  destination: p.destination,
  duration: p.duration || "1 Week",
  tagline: p.tagline || \`Executive training in \${p.category}\`,
  summary: p.summary || \`\${p.title}. Target: \${p.target}. Schedule: \${p.schedule}.\`,
  audience: p.audience || [p.target],
  indicativeStructure: p.indicativeStructure || [
    "Module 1: Strategic Foundations & Industry Context",
    "Module 2: Operational Methods & Capacity Development",
    "Module 3: Leadership Implementation & Case Workshop",
  ],
  outcomes: p.outcomes || [
    "Enhanced operational capability and strategic understanding",
    "Applied framework ready for immediate institutional deployment",
    "Official GIBS Certificate of Completion accredited by CMD & ITF",
  ],
  format: p.format || "Interactive Workshop & Seminar",
  startDate: p.startDate || p.schedule,
  requirements: p.requirements || "Nomination by sponsoring organization or self-sponsorship",
  faqs: p.faqs || [
    {
      q: "Who should attend this programme?",
      a: p.target,
    },
    {
      q: "Where is this programme scheduled?",
      a: \`Scheduled for \${p.schedule} at \${p.location}.\`,
    },
  ],
  officialOnly: p.officialOnly || ["Venue confirmation", "Nomination portal link"],
});

export const LOCAL_PROGRAMMES: Programme[] = [
  // ACCOUNTING AND FINANCIAL MANAGEMENT
  makeProgramme({
    number: 1,
    slug: "public-sector-accounting-procedure-and-standards",
    title: "Public Sector Accounting Procedure and Standards",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "March 2–6 (Ibafo), April 13–17 (Ilorin), Sept 7–11 (Abuja)",
    location: "Ibafo / Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 2,
    slug: "accounts-reconciliation-technique-and-cash-management",
    title: "Accounts Reconciliation Technique and Cash Management Strategies for Accounting and Financial Reporting Efficiency",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "March 9–13 (Ibafo), April 13–17 (Ilorin), Sept 7–11 (Abuja)",
    location: "Ibafo / Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 3,
    slug: "finance-for-non-finance-staff",
    title: "Finance for Non-Finance Staff",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement",
    schedule: "April 13–17 (Ilorin), July 20–24 (Keffi), Aug 3–7 (Abuja), Oct 12–16 (Lagos)",
    location: "Ilorin / Keffi / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 4,
    slug: "public-sector-budgeting-and-budget-reforms",
    title: "Public Sector Budgeting and Budget Reforms & Implementation Efficiency",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior Management Staff - Finance, Audit, Procurement Dept.",
    schedule: "April 13–17 (Ibafo), June 1–5 (Abuja), Oct 5–9 (Ilorin)",
    location: "Ibafo / Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 5,
    slug: "corporate-social-responsibility-mdas",
    title: "Corporate Social Responsibility For the Private and Public Sectors (MDAs)",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff - ALL Departments",
    schedule: "March 9–13 (Abuja), April 6–10 (Ibafo), Aug 31–Sept 4 (Ilorin)",
    location: "Abuja / Ibafo / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 6,
    slug: "financial-management-skills-and-strategies-public-sector",
    title: "Financial Management Skills & Strategies in the Public Sector",
    category: "Accounting & Financial Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "All Staff",
    schedule: "May 4–8 (Keffi), Aug 10–14 (Abuja), Dec 7–11 (Lagos)",
    location: "Keffi / Abuja / Lagos",
    destination: "Nigeria",
  }),

  // GENERAL ADMINISTRATION AND MANAGEMENT
  makeProgramme({
    number: 7,
    slug: "customer-relationship-management-and-retention",
    title: "Customer Relationship Management and Retention",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 18–22 (Ibafo), Aug 17–21 (Abuja), Oct 5–9 (Ilorin)",
    location: "Ibafo / Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 8,
    slug: "translating-policies-into-economic-transformation",
    title: "Translating Policies into Economic Transformation of Public and Private Sectors' Economy",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Abuja), Aug 3–7 (Ilorin), Nov 2–6 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 9,
    slug: "a-modern-approach-to-procurement-strategic-perspective",
    title: "A Modern Approach to Procurement: A Strategic Perspective",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "Jul 6–10 (Abuja), Aug 3–7 (Ibafo), Oct 5–9 (Ilorin)",
    location: "Abuja / Ibafo / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 10,
    slug: "middle-level-management-techniques-new-perspectives",
    title: "Middle Level Management Techniques: New Perspectives",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Ibafo), July 6–10 (Ilorin), Oct 19–23 (Abuja), Nov 30–Dec 4 (Keffi)",
    location: "Ibafo / Ilorin / Abuja / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 11,
    slug: "next-generation-hr-aligning-hr-to-strategy",
    title: "Next Generation HR: Aligning HR to Strategy: Transforming Human Resources to Human Capital",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "HR, Admin, Procurement, Senior & Middle level Mgt Staff",
    schedule: "April 20–24 (Ibafo), July 6–10 (Ilorin), Oct 12–16 (Abuja)",
    location: "Ibafo / Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 12,
    slug: "ethical-standards-and-organisational-development",
    title: "Ethical Standards and Organisational Development in the Public Service",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "July 13–17 (Keffi), Aug 24–28 (Abuja), Oct 12–16 (Ilorin), Nov 30–Dec 4 (Lagos)",
    location: "Keffi / Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 13,
    slug: "improved-productivity-based-on-good-performance-culture",
    title: "Improved Productivity Based on a Good Performance Culture",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff - ALL Depts.",
    schedule: "Sept 7–11 (Abuja), Oct 12–16 (Ibafo), Nov 23–27 (Lagos)",
    location: "Abuja / Ibafo / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 14,
    slug: "pension-administration-and-management-strategies",
    title: "Pension Administration and Management Strategies",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦350,000",
    currency: "NGN",
    feeAmount: 350000,
    target: "Senior & Middle level Mgt Staff - ALL Depts.",
    schedule: "May 4–8 (Ilorin), July 13–17 (Abuja), Oct 19–23 (Keffi)",
    location: "Ilorin / Abuja / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 15,
    slug: "building-strong-financial-management-strategies",
    title: "Building Strong Financial Management Strategies to Sustain Organisational Growth",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "April 13–17 (Abuja), July 13–17 (Ilorin), Sept 14–18 (Ibafo)",
    location: "Abuja / Ilorin / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 16,
    slug: "pre-and-post-service-empowerment-training-programme",
    title: "Pre & Post Service Empowerment Training Programme - (2 Weeks)",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦800,000",
    currency: "NGN",
    feeAmount: 800000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Nov 23–27 (Lagos), Mar 23–April 4 (Ibafo)",
    location: "Lagos / Ibafo",
    destination: "Nigeria",
    duration: "2 Weeks",
  }),
  makeProgramme({
    number: 17,
    slug: "interpersonal-relationships-skills",
    title: "Interpersonal Relationships Skills",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 8–12 (Abuja), Aug 17–21 (Ilorin), Oct 19–23 (Keffi), Nov 30–Dec 4 (Lagos)",
    location: "Abuja / Ilorin / Keffi / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 18,
    slug: "public-and-private-sector-corporate-governance",
    title: "Public and Private Sector Corporate Governance",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "May 11–15 (Ilorin), Aug 10–14 (Abuja), Sept 14–18 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 19,
    slug: "public-sector-management-making-reforms-effective",
    title: "Public Sector Management: Making Reforms Effective",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Ilorin), Sept 14–18 (Abuja), Nov 23–27 (Lagos), Nov 30–Dec 4 (Keffi)",
    location: "Ilorin / Abuja / Lagos / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 20,
    slug: "strategic-leadership-through-technological-innovation",
    title: "Strategic Leadership Through Technological Innovation Workshop",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 18–22 (Abuja), Aug 24–28 (Ibafo), Oct 5–9 (Ilorin)",
    location: "Abuja / Ibafo / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 21,
    slug: "leading-high-performing-teams-for-improved-productivity",
    title: "Leading High Performing Teams For Improved Productivity Workshop",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦395,000",
    currency: "NGN",
    feeAmount: 395000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Abuja), Oct 12–16 (Lagos), Nov 2–6 (Keffi), Dec 7–11 (Ilorin)",
    location: "Abuja / Lagos / Keffi / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 22,
    slug: "preparing-for-retirement-from-the-beginning",
    title: "Preparing For Retirement from the Beginning",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Abuja), Oct 12–16 (Ilorin), Nov 9–13 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 23,
    slug: "emerging-trends-in-hrm-post-covid-19-approaches",
    title: "Emerging Trends in Human Resources Management: Post Covid-19 Approaches",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Keffi), Aug 10–14 (Ilorin), Oct 12–16 (Abuja)",
    location: "Keffi / Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 24,
    slug: "train-the-trainers-workshop-2-weeks",
    title: "Train-the-Trainers Workshop – (2 Weeks)",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦800,000",
    currency: "NGN",
    feeAmount: 800000,
    target: "HR, Training & Admin Staff",
    schedule: "March 16–20 (Ilorin), Sept 7–11 (Abuja), Oct 12–16 (Ibafo)",
    location: "Ilorin / Abuja / Ibafo",
    destination: "Nigeria",
    duration: "2 Weeks",
  }),
  makeProgramme({
    number: 25,
    slug: "emotional-intelligence-and-productivity-in-work-place",
    title: "Emotional Intelligence and Productivity in Work Place",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Abuja), Sept 14–18 (Keffi), Nov 2–6 (Lagos), Nov 30–Dec 4 (Abuja & Keffi)",
    location: "Abuja / Keffi / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 26,
    slug: "emerging-trends-in-board-room-management",
    title: "Emerging Trends in Board Room Management: Roles of Company Secretary and Board Effectiveness",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Staff of CEO & ECs (SAs) office, and Commission Secretariat",
    schedule: "July 6–10 (Abuja), Oct 5–9 (Ilorin), Nov 9–13 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 27,
    slug: "management-of-virtual-business-models",
    title: "Management of Virtual Business Models in the Private and Public Sectors: Future Prerequisite For Self-Employment",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 18–22 (Ilorin)",
    location: "Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 28,
    slug: "developing-leadership-competencies-for-improved-productivity",
    title: "Developing Leadership Competencies for Improved Productivity",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Sept 21–25 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 29,
    slug: "effective-communication-skills-for-staff",
    title: "Effective Communication Skills for Staff in the Public and Private Sector",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 22–26 (Abuja), Sept 7–11 (Lagos), Nov 9–13 (Ilorin), Dec 7–11 (Lagos)",
    location: "Abuja / Lagos / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 30,
    slug: "report-writing-and-presentation-skills",
    title: "Report Writing and Presentation Skills for Staff in the Public and Private Sector",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "All Staff",
    schedule: "June 1–5 (Ilorin), Aug 17–21 (Abuja), Oct 12–16 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 31,
    slug: "office-ethics-and-worklife-balance-for-staff",
    title: "Workshop on Office Ethics and WorkLife Balance for Staff",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff ALL - Depts.",
    schedule: "July 20–24 (Ilorin), Oct 19–23 (Lagos), Nov 30–Dec 4 (Abuja)",
    location: "Ilorin / Lagos / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 32,
    slug: "ict-tools-as-enabler-for-improved-productivity",
    title: "ICT Tools as Enabler For Improved Productivity in the Workplace",
    category: "General Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff ALL - Depts.",
    schedule: "June 22–26 (Keffi), Aug 10–14 (Abuja), Oct 26–30 (Lagos), Nov 30–Dec 4 (Ilorin)",
    location: "Keffi / Abuja / Lagos / Ilorin",
    destination: "Nigeria",
  }),

  // TELECOM AND OTHER UTILITIES REGULATION
  makeProgramme({
    number: 33,
    slug: "regulatory-and-operational-strategies-for-telecom-executives",
    title: "Regulatory and Operational Strategies for Telecom Executives",
    category: "Telecom & Utilities Regulation",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Board Members and Executive Management Staff",
    schedule: "May 11–15 (Ilorin), Aug 3–7 (Lagos), Oct 5–9 (Abuja)",
    location: "Ilorin / Lagos / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 34,
    slug: "next-generation-challenges-and-opportunities-telecom-executives",
    title: "Next Generation Challenges & Opportunities for Telecom Senior Executives",
    category: "Telecom & Utilities Regulation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Board Members and Executive Management Staff",
    schedule: "Aug 17–21 (Ilorin), Oct 12–16 (Abuja), Dec 7–11 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 35,
    slug: "effective-leadership-and-corporate-governance-directors",
    title: "Effective Leadership and Corporate Governance For Directors & Senior Management Staff",
    category: "Telecom & Utilities Regulation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 6–10 (Ilorin), Sept 14–18 (Abuja), Oct 19–23 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 36,
    slug: "regulatory-compliance-monitoring-and-enforcement",
    title: "Regulatory Compliance Monitoring and Enforcement in Telecom, Power, Pension and Basic Sectors of the Economy",
    category: "Telecom & Utilities Regulation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Board Members and Executive Management Staff",
    schedule: "April 20–24 (Abuja), July 13–17 (Ilorin), Sept 14–18 (Abuja & Ibafo), Oct 19–23 (Lagos)",
    location: "Abuja / Ilorin / Ibafo / Lagos",
    destination: "Nigeria",
  }),

  // CONSUMERS PROTECTION APPRECIATION
  makeProgramme({
    number: 37,
    slug: "economics-of-regulation-and-rates-determination",
    title: "Economics of Regulation and Rates Determination For Utilities Management",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Abuja), Nov 9–13 (Lagos)",
    location: "Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 38,
    slug: "regulations-and-consumer-protection-in-nigerian-economy",
    title: "Regulations and Consumer Protection in the Nigerian Economy: Prospects and Challenges",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 15–19 (Abuja), Aug 10–14 (Lagos), Sept 14–18 (Ilorin), Nov 16–20 (Abuja)",
    location: "Abuja / Lagos / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 39,
    slug: "telecom-for-beginners-and-non-engineers",
    title: "Telecom For Beginners and Non-Engineers",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Snr/Middle Level Mgt Staff",
    schedule: "June 15–19 (Abuja), Aug 17–21 (Ilorin), Oct 19–23 (Abuja), Nov 9–13 (Lagos), Nov 30–Dec 4 (Ilorin)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 40,
    slug: "code-of-practice-regulation-for-regulators",
    title: "Code of Practice Regulation For Regulators: Public and Private sectors of the Nigerian Economy",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Aug 17–21 (Ibafo), Oct 19–23 (Abuja)",
    location: "Ibafo / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 41,
    slug: "regulation-and-protection-strategies-in-telecom-power",
    title: "Regulation and Protection Strategies in Telecom, Power and other Utilities",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 20–24 (Ilorin), Oct 12–16 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 42,
    slug: "evaluation-of-quality-of-experience-of-consumers",
    title: "Evaluation of Quality of Experience of Consumers – Feeling the Pulse",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Ilorin), Aug 17–21 (Abuja), Oct 26–30 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 43,
    slug: "cyber-crime-and-cyber-security-prospects-and-challenges",
    title: "Cyber Crime and Cyber Security: Prospects & Challenges",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 20–24 (Ilorin), Sept 14–18 (Ibafo), Oct 12–16 (Abuja), Nov 16–20 (Lagos), Dec 7–11 (Abuja)",
    location: "Ilorin / Ibafo / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 44,
    slug: "capacity-building-workshop-on-ict-literacy-and-security",
    title: "Capacity-Building Workshop on ICT Literacy and Security Awareness",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "July 13–17 (Ilorin), Aug 10–14 (Abuja), Sept 14–18 (Lagos), Nov 2–6 (Abuja), Dec 7–11 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 45,
    slug: "managing-consumer-expectations-and-customer-retention",
    title: "Managing Consumer Expectations & Customer Retention",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Aug 17–21 (Abuja), Oct 12–16 (Lagos), Nov 9–13 (Keffi)",
    location: "Abuja / Lagos / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 46,
    slug: "customers-experience-management-workshop",
    title: "Customers Experience Management Workshop",
    category: "Consumer Protection & Engagement",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 6–10 (Lagos), Sept 7–11 (Abuja), Oct 19–23 (Ilorin), Nov 23–27 (Abuja)",
    location: "Lagos / Abuja / Ilorin",
    destination: "Nigeria",
  }),

  // ENVIRONMENTAL SUSTAINABILITY AND MANAGEMENT
  makeProgramme({
    number: 47,
    slug: "telecom-installations-and-radiation-environmental-impact",
    title: "Telecom Installations and Radiation: Environmental Impact, Assessment and Quality",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Ilorin), July 6–10 (Abuja), Sept 14–18 (Ibafo), Oct 26–30 (Lagos)",
    location: "Ilorin / Abuja / Ibafo / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 48,
    slug: "global-environmental-change-and-development-impact",
    title: "Global Environmental Change and Development Impact",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦350,000",
    currency: "NGN",
    feeAmount: 350000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "March 16–20 (Ilorin), Aug 10–14 (Abuja), Nov 9–13 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 49,
    slug: "environmental-sustainability-and-development-strategies",
    title: "Environmental Sustainability and Development Strategies",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "March 23–27 (Ibafo), Nov 16–20 (Ilorin)",
    location: "Ibafo / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 50,
    slug: "environmental-protection-issues-prospects-and-challenges",
    title: "Environmental Protection Issues - Prospects and Challenges: Draught, Deforestation, Afforestation, Desert Encroachment, Water and Air Pollution, Oil Spillage, Erosion Control Mechanism",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 4–8 (Ibafo), July 6–10 (Abuja), Sept 7–11 (Ilorin)",
    location: "Ibafo / Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 51,
    slug: "climate-change-and-agricultural-development-strategies",
    title: "Climate Change and Agricultural Development Strategies",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦350,000",
    currency: "NGN",
    feeAmount: 350000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "March 23–27 (Ilorin), Nov 2–6 (Ibafo)",
    location: "Ilorin / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 52,
    slug: "soil-management-and-food-production-techniques",
    title: "Soil Management and Food Production Techniques",
    category: "Environmental Sustainability & Management",
    programmeType: "Local/Open",
    fee: "₦300,000",
    currency: "NGN",
    feeAmount: 300000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Nov 16–20 (Ilorin)",
    location: "Ilorin",
    destination: "Nigeria",
  }),

  // OIL AND GAS SECTOR
  makeProgramme({
    number: 53,
    slug: "international-oil-and-gas-development-strategies",
    title: "International Oil and Gas Development Strategies: Upstream / Downstream Segments",
    category: "Oil & Gas Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "HR, Admin, Procurement, Senior & Middle level Mgt Staff",
    schedule: "Aug 3–7 (Abuja), Oct 5–9 (Ibafo)",
    location: "Abuja / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 54,
    slug: "local-content-development-strategies-in-oil-and-gas",
    title: "Local Content Development Strategies in the Oil and Gas Industry",
    category: "Oil & Gas Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "June 8–12 (Ilorin), Oct 5–9 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 55,
    slug: "building-capacity-in-environmental-management-oil-and-gas",
    title: "Building Capacity in Environmental Management: Best Practices in the Oil and Gas Industry",
    category: "Oil & Gas Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "May 11–15 (Abuja), July 13–17 (Lagos), Sept 7–11 (Abuja), Nov 9–13 (Lagos)",
    location: "Abuja / Lagos",
    destination: "Nigeria",
  }),

  // SECRETARIAL ADMINISTRATION AND MANAGEMENT
  makeProgramme({
    number: 56,
    slug: "skill-enhancement-for-secretaries-and-pas",
    title: "Skill Enhancement for Secretaries and PAs",
    category: "Secretarial Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Secretaries",
    schedule: "July 13–17 (Abuja), Aug 3–7 (Ilorin), Oct 5–9 (Keffi), Nov 16–20 (Lagos)",
    location: "Abuja / Ilorin / Keffi / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 57,
    slug: "modern-secretarial-administration-techniques",
    title: "Modern Secretarial Administration Techniques in the Computerisation Era",
    category: "Secretarial Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Secretaries",
    schedule: "June 1–5 (Ilorin), Aug 17–21 (Abuja), Oct 12–16 (Keffi)",
    location: "Ilorin / Abuja / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 58,
    slug: "executive-secretarial-management-new-strategies",
    title: "Executive Secretarial Management: The New Strategies",
    category: "Secretarial Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior level Secretaries",
    schedule: "June 8–12 (Ilorin), Sept 7–11 (Abuja), Nov 2–6 (Ibafo), Nov 30–Dec 4 (Keffi)",
    location: "Ilorin / Abuja / Ibafo / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 59,
    slug: "excel-and-power-point-preparation-skill-for-secretaries",
    title: "Excel and Power Point Preparation Skill for Secretaries",
    category: "Secretarial Administration & Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Secretaries, PAs",
    schedule: "May 18–22 (Ilorin), Oct 5–9 (Ibafo)",
    location: "Ilorin / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 60,
    slug: "basic-management-workshop-for-secretaries-and-pas",
    title: "Basic Management Workshop For Secretaries and Personal Assistants",
    category: "Secretarial Administration & Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Secretaries, PAs",
    schedule: "June 8–12 (Abuja), Aug 31–Sept 4 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),

  // CAPITAL MARKET / SECURITIES & STOCK MANAGEMENT
  makeProgramme({
    number: 61,
    slug: "capital-market-development-and-regulations",
    title: "Capital Market: Development and Regulations",
    category: "Capital Market & Securities",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 11–15 (Abuja), Aug 3–7 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 62,
    slug: "securities-stock-market-development-and-management",
    title: "Securities/Stock Market Development and Management",
    category: "Capital Market & Securities",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 1–5 (Abuja), Nov 9–13 (Ibafo)",
    location: "Abuja / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 63,
    slug: "capital-market-management-foundation-of-development",
    title: "Capital Market Management: Foundation of Development and Regulation",
    category: "Capital Market & Securities",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff - Finance, Audit, Procurement Dept.",
    schedule: "Aug 3–7 (Ilorin), Sept 7–11 (Abuja), Nov 16–20 (Ibafo)",
    location: "Ilorin / Abuja / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 64,
    slug: "alternative-securities-market-raising-capital",
    title: "Alternative Securities Market: Raising Capital for Businesses",
    category: "Capital Market & Securities",
    programmeType: "Local/Open",
    fee: "₦350,000",
    currency: "NGN",
    feeAmount: 350000,
    target: "All Staff",
    schedule: "June 8–12 (Lagos), Nov 2–6 (Ilorin)",
    location: "Lagos / Ilorin",
    destination: "Nigeria",
  }),

  // INFORMATION TECHNOLOGY WORKSHOPS
  makeProgramme({
    number: 65,
    slug: "strategies-against-cybersecurity-vulnerability",
    title: "Strategies Against Cybersecurity Vulnerability and Threats",
    category: "Information Technology",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior and Middle Level Staff",
    schedule: "July 13–17 (Keffi), Aug 17–21 (Abuja), Oct 5–9 (Ibafo), Dec 7–11 (Lagos)",
    location: "Keffi / Abuja / Ibafo / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 66,
    slug: "microsoft-excel-for-managers-intermediate",
    title: "Microsoft Excel For Managers, Accountants, Statisticians: Intermediate",
    category: "Information Technology",
    programmeType: "Local/Open",
    fee: "₦300,000",
    currency: "NGN",
    feeAmount: 300000,
    target: "Senior Level Staff",
    schedule: "June 1–5 (Abuja), Nov 2–6 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 67,
    slug: "microsoft-excel-for-managers-advanced",
    title: "Microsoft Excel For Managers, Accountants, Statisticians: Advanced",
    category: "Information Technology",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior Level Staff",
    schedule: "Aug 3–7 (Ibafo), Sept 14–18 (Ilorin), Nov 16–20 (Abuja)",
    location: "Ibafo / Ilorin / Abuja",
    destination: "Nigeria",
  }),

  // LEGAL AND LEGISLATIVE
  makeProgramme({
    number: 68,
    slug: "role-of-public-servants-in-legal-political-development",
    title: "The Role of Public Servants in Legal, Political and Social Development in Nigeria",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 15–19 (Abuja), Aug 10–14 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 69,
    slug: "public-service-in-a-constitutional-democracy",
    title: "Public Service in a Constitutional Democracy: The Prospects and Challenges",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "March 9–13 (Ilorin), July 20–24 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 70,
    slug: "fundamentals-of-legislative-drafting",
    title: "Fundamentals of Legislative Drafting",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Legal Dept. Staff",
    schedule: "Oct 19–23 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 71,
    slug: "rule-of-law-and-good-governance",
    title: "Rule of Law and Good Governance",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Sept 14–18 (Ilorin)",
    location: "Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 72,
    slug: "law-makers-and-legislative-process",
    title: "Law Makers and Legislative Process",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Legislators & Related Staff",
    schedule: "Apr 13–17 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 73,
    slug: "law-making-as-a-catalyst-for-national-development",
    title: "Law Making as a Catalyst for National Development",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Legislators & Related Staff",
    schedule: "Apr 20–24 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 74,
    slug: "legislature-as-sustainers-of-democracy",
    title: "Legislature as Sustainers of Democracy",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Legislators & Related Staff",
    schedule: "June 15–19 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 75,
    slug: "orientation-and-induction-for-legislators",
    title: "Orientation and Induction for Legislators",
    category: "Legal & Legislative",
    programmeType: "Local/Open",
    fee: "₦600,000",
    currency: "NGN",
    feeAmount: 600000,
    target: "Legislators & Related Staff",
    schedule: "June 22–26 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),

  // POWER AND ENERGY SECTOR COURSES
  makeProgramme({
    number: 76,
    slug: "international-oil-and-gas-management-development-strategies",
    title: "International Oil and Gas Management Development Strategies: Upstream / Downstream Segments",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "HR, Admin, Procurement, Senior & Middle level Mgt Staff",
    schedule: "April 13–17 (Ibafo), July 13–17 (Abuja)",
    location: "Ibafo / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 77,
    slug: "building-capacity-in-environmental-management-oil-gas",
    title: "Building Capacity in Environmental Management: Best Practices in the Oil and Gas Industry",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "May 11–15 (Lagos), Aug 17–21 (Lagos), Nov 9–13 (Abuja)",
    location: "Lagos / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 78,
    slug: "power-sector-reforms-and-economic-development",
    title: "Power Sector Reforms and the Impacts on Economic Development of the Nation",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 15–19 (Abuja), Sept 7–11 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 79,
    slug: "unbundling-the-power-sector-prospects-for-economic-growth",
    title: "Unbundling the Power Sector: Prospects For Economic Growth",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Abuja)",
    location: "Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 80,
    slug: "tariff-and-rate-setting-management-for-utilities",
    title: "Tariff and Rate Setting Management For Utilities (Telecoms and Power Sectors): The Impact on Customers",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Aug 24–28 (Lagos), Nov 9–13 (Abuja)",
    location: "Lagos / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 81,
    slug: "best-practices-and-performance-management-power-sector",
    title: "Best Practices and Performance Management for Strategic Improvements in the Power Sector (Electricity and Oil & Gas Industry)",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 8–12 (Abuja), Nov 16–20 (Ibafo)",
    location: "Abuja / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 82,
    slug: "corporate-governance-as-corruption-mitigation-strategy",
    title: "Corporate Governance as a Potent Corruption Prevention and Mitigation Strategy in the Energy and Telecom Sectors",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "April 13–17 (Ilorin), Sept 21–25 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 83,
    slug: "specialised-train-the-trainers-workshop-utility-managers",
    title: "Specialised Train - The Trainers Workshop for the Utility Managers in all sectors of the Economy",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 15–19 (Abuja), Oct 12–16 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 84,
    slug: "effective-corporate-communication-telecom-oil-power",
    title: "Effective Corporate Communication For The Telecom, Oil & Gas, and Power & Energy Sectors",
    category: "Power & Energy Sector",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "June 15–19 (Abuja), Nov 16–20 (Ibafo)",
    location: "Abuja / Ibafo",
    destination: "Nigeria",
  }),

  // MARITIME / TRANSPORTATION
  makeProgramme({
    number: 85,
    slug: "strategic-planning-protection-marine-environment",
    title: "Strategic Planning for the Protection of Marine Environment: Prospects and Challenges",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "Aug 3–7 (Abuja), Oct 5–9 (Lagos & Ibafo)",
    location: "Abuja / Lagos / Ibafo",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 86,
    slug: "leadership-role-for-ports-managers-improved-productivity",
    title: "Leadership Role for Ports Managers for Improved Productivity",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "June 1–5 (Ibafo), Oct 12–16 (Abuja)",
    location: "Ibafo / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 87,
    slug: "economic-importance-of-ports-to-national-development",
    title: "Economic Importance of Ports to National Development",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "May 18–22 (Ibafo), Nov 2–6 (Abuja)",
    location: "Ibafo / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 88,
    slug: "building-capacity-environmental-management-maritime",
    title: "Building Capacity in Environmental Management: Best Practices in the Maritime Industry – NPA, NIMASA, Shippers Council, etc.",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "June 15–19 (Ibafo), Aug 10–14 (Abuja), Oct 12–16 (Lagos & Ibafo)",
    location: "Ibafo / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 89,
    slug: "managing-infractions-at-seaports-for-improved-productivity",
    title: "Managing Infractions at the Seaports For Improved Productivity",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "April 6–10 (Lagos), July 13–17 (Ilorin), Sept 14–18 (Abuja)",
    location: "Lagos / Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 90,
    slug: "revenue-generation-strategies-for-maritime-sector",
    title: "Revenue Generation Strategies for Maritime Sector Players",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "May 11–15 (Abuja), July 13–17 (Lagos), Nov 16–20 (Ilorin)",
    location: "Abuja / Lagos / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 91,
    slug: "modern-strategies-managing-environmental-hazards-seaports",
    title: "Modern Strategies For Managing Environmental Hazards At The Seaports",
    category: "Maritime & Transportation",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "Aug 10–14 (Lagos)",
    location: "Lagos",
    destination: "Nigeria",
  }),

  // PENSION MANAGEMENT
  makeProgramme({
    number: 92,
    slug: "strategic-thinking-compliance-pensionable-workers",
    title: "Strategic Thinking For Ensuring Compliance of Employers of Pensionable Workers for Service Delivery – PENCOM & PFAs, CPFAs",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "May 11–15 (Ilorin), Aug 10–14 (Abuja), Oct 19–23 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 93,
    slug: "critical-thinking-and-problem-solving-pension-managers",
    title: "Critical Thinking and Problem Solving for Pension Managers and Regulators",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "June 8–12 (Ilorin), Oct 5–9 (Abuja)",
    location: "Ilorin / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 94,
    slug: "effective-communication-capacity-building-pension-administrators",
    title: "Effective Communication and Capacity Building For Pension Administrators and Regulators",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Top/Senior & Middle Level Mgt",
    schedule: "May 18–22 (Ilorin), Sept 14–18 (Lagos), Nov 9–13 (Abuja)",
    location: "Ilorin / Lagos / Abuja",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 95,
    slug: "current-strategies-pension-administration-service-delivery",
    title: "Current Strategies For Pension Administration For Effective Service Delivery",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Senior & Middle Level Mgt Staff – ALL Depts.",
    schedule: "May 11–15 (Abuja), July 20–24 (Lagos), Oct 19–23 (Keffi)",
    location: "Abuja / Lagos / Keffi",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 96,
    slug: "strategies-for-effective-business-communication",
    title: "Strategies for Effective Business Communication",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "All Staff",
    schedule: "May 11–15 (Ilorin), Aug 17–21 (Abuja), Oct 12–16 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 97,
    slug: "next-generation-challenges-pension-administrators",
    title: "Next Generation Challenges & Opportunities for Pension Administrators",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦300,000",
    currency: "NGN",
    feeAmount: 300000,
    target: "Senior & Middle level Mgt Staff",
    schedule: "July 13–17 (Ilorin), Sept 14–18 (Abuja), Oct 19–23 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 98,
    slug: "regulatory-and-operational-strategies-pension-managers",
    title: "Regulatory and Operational Strategies for Pension Managers and Executives",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Middle level and Senior Management Staff",
    schedule: "May 11–15 (Ilorin), Aug 10–14 (Abuja), Oct 19–23 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 99,
    slug: "workshop-on-office-management-and-administrative-skills",
    title: "Workshop on Office Management and Administrative Skills",
    category: "Pension Management",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Middle and Senior Level Staff",
    schedule: "July 13–17 (Abuja), Sept 7–11 (Ilorin), Nov 30–Dec 4 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),

  // SELECTED SPECIAL TRAINING PROGRAMME
  makeProgramme({
    number: 100,
    slug: "communication-presentations-public-relations-skills",
    title: "Communication / Presentations and Public Relations Skills",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "Middle and Senior Level Staff",
    schedule: "May 4–8 (Abuja), Aug 17–21 (Lagos)",
    location: "Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 101,
    slug: "advanced-public-speaking-and-presentation-skills",
    title: "Advanced Public Speaking and Presentation Skills",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "Protocols, EAs & PAs",
    schedule: "July 6–10 (Ilorin), Oct 12–16 (Lagos)",
    location: "Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 102,
    slug: "enhancing-office-etiquette-for-improved-productivity",
    title: "Enhancing Office Etiquette For Improved Productivity",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦390,000",
    currency: "NGN",
    feeAmount: 390000,
    target: "All Staff",
    schedule: "Aug 10–14 (Ilorin), Nov 23–27 (Lagos)",
    location: "Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 103,
    slug: "ethical-standards-and-organisational-development-public-service",
    title: "Ethical Standards and Organisational Development in the Public Service",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦400,000",
    currency: "NGN",
    feeAmount: 400000,
    target: "All Staff",
    schedule: "Aug 24–28 (Abuja), Oct 12–16 (Ilorin), Nov 30–Dec 4 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 104,
    slug: "next-generation-digital-strategies-and-ict-applications",
    title: "Next Generation Digital Strategies and ICT Applications",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "July 6–10 (Ilorin), Aug 24–28 (Abuja), Oct 12–16 (Ilorin), Nov 30–Dec 4 (Lagos)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 105,
    slug: "project-management-essentials-prospects-and-challenges",
    title: "Project Management Essentials: Prospects and Challenges",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "July 6–10 (Ilorin), Sept 21–25 (Abuja), Oct 12–16 (Lagos), Dec 7–11 (Ilorin)",
    location: "Ilorin / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 106,
    slug: "monitoring-and-impact-evaluation-workshop",
    title: "Monitoring and Impact Evaluation Workshop",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "Aug 24–28 (Abuja), Oct 12–16 (Ilorin), Nov 30–Dec 4 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 107,
    slug: "procurement-and-vendor-management-skills-workshop",
    title: "Procurement and Vendor Management Skills Workshop",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Relevant Staff",
    schedule: "June 15–19 (Abuja), Sept 14–18 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 108,
    slug: "resolving-contractual-claims-and-disputes",
    title: "Resolving Contractual Claims and Disputes",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Relevant Staff",
    schedule: "June 15–19 (Abuja), Sept 14–18 (Ilorin)",
    location: "Abuja / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 109,
    slug: "basic-data-analytics-for-business-and-financial-analysts",
    title: "Basic Data Analytics for Business and Financial Analysts",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "Relevant Staff",
    schedule: "July 27–31 (Abuja), Oct 19–23 (Lagos), Dec 7–11 (Abuja)",
    location: "Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 110,
    slug: "software-disaster-and-contingency-planning-workshop",
    title: "Software Disaster and Contingency Planning Workshop",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "Nov 30–Dec 4 (Keffi), Dec 7–11 (Abuja & Lagos)",
    location: "Keffi / Abuja / Lagos",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 111,
    slug: "organizational-design-and-development",
    title: "Organizational Design & Development",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "July 13–17 (Abuja), Oct 12–16 (Lagos), Nov 2–6 (Keffi), Dec 7–11 (Ilorin)",
    location: "Abuja / Lagos / Keffi / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 112,
    slug: "delivering-value-through-people-public-private-sectors",
    title: "Delivering Value through People in the Public and Private Sectors",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "June 22–26 (Abuja), Sept 7–11 (Lagos), Nov 9–13 (Ilorin), Dec 7–11 (Lagos)",
    location: "Abuja / Lagos / Ilorin",
    destination: "Nigeria",
  }),
  makeProgramme({
    number: 113,
    slug: "introductory-data-analytics-for-pension-administrators",
    title: "Introductory Data Analytics for Pension Administrators",
    category: "Special Training Programmes",
    programmeType: "Local/Open",
    fee: "₦450,000",
    currency: "NGN",
    feeAmount: 450000,
    target: "All Staff",
    schedule: "June 15–19 (Abuja), Sept 14–18 (Ilorin), Nov 16–20 (Abuja), Dec 7–11 (Lagos)",
    location: "Abuja / Ilorin / Lagos",
    destination: "Nigeria",
  }),
];

export const FOREIGN_PROGRAMMES: Programme[] = [
  // KIGALI – RWANDA (8 Programmes)
  makeProgramme({
    slug: "kigali-managing-service-quality-and-customer-satisfaction",
    title: "Managing Service Quality and Customer Satisfaction in the Public and Private Sector",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Aug 3–7, Nov 9–13",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-capacity-building-ict-literacy-and-security",
    title: "Capacity Building Workshop on ICT Literacy and Security Awareness",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "All Staff",
    schedule: "June 22–26, Oct 12–16",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-business-process-management-strategies",
    title: "Business Process Management Strategies in Public and Private Sectors",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Sept 7–11",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-ethical-standards-and-organisational-development",
    title: "Ethical Standards and Organisational Development in the Public Service and the Private Sector",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Aug 10–14, Nov 30–Dec 4",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-customer-relationship-management-and-retention",
    title: "Customer Relationship Management and Retention",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "All Staff",
    schedule: "Aug 10–14, Oct 20–24",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-regulatory-compliance-monitoring-and-enforcement",
    title: "Regulatory Compliance Monitoring and Enforcement in Telecom, Power, Pension and Basic Sectors of the Economy",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "All Staff",
    schedule: "Aug 25–29, Oct 19–23, Nov 23–27",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-next-generation-digital-strategies-and-ict",
    title: "Next Generation Digital Strategies and ICT Applications for Improved Productivity in the Work Place",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "All Staff",
    schedule: "Aug 24–28, Nov 16–20",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),
  makeProgramme({
    slug: "kigali-regulatory-and-operational-strategies-utility-managers",
    title: "Regulatory and Operational Strategies for Utility Managers and Regulators",
    category: "Kigali Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "All Staff",
    schedule: "July 20–24, Oct 5–9",
    location: "Kigali, Rwanda",
    destination: "Kigali",
  }),

  // DUBAI – UAE (5 Programmes)
  makeProgramme({
    slug: "dubai-developing-management-skills-for-administrators",
    title: "Developing Management Skills For Administrators, SAs, PAs and Secretaries",
    category: "Dubai Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "July 20–24, Nov 16–20",
    location: "Dubai, UAE",
    destination: "Dubai",
  }),
  makeProgramme({
    slug: "dubai-modern-secretarial-administration-techniques",
    title: "Modern Secretarial Administration Techniques in the Computerisation Era",
    category: "Dubai Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Secretaries, PAs, EAs",
    schedule: "July 20–24, Nov 16–20",
    location: "Dubai, UAE",
    destination: "Dubai",
  }),
  makeProgramme({
    slug: "dubai-next-generation-challenges-telecom-utility-managers",
    title: "Next Generation Challenges & Opportunities for Telecom Other Utility Managers",
    category: "Dubai Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Relevant Staff",
    schedule: "Sept 7–11, Oct 12–16",
    location: "Dubai, UAE",
    destination: "Dubai",
  }),
  makeProgramme({
    slug: "dubai-leadership-and-management-innovation-using-ict",
    title: "Leadership and Management Innovation For Organisational Development Using ICT",
    category: "Dubai Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Aug 24–28, Oct 12–16",
    location: "Dubai, UAE",
    destination: "Dubai",
  }),
  makeProgramme({
    slug: "dubai-interpersonal-skills-effective-communication",
    title: "Interpersonal Skills For Effective Communication and Confidence Building",
    category: "Dubai Hub",
    programmeType: "Foreign",
    fee: "$4,800 USD",
    currency: "USD",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Sept 21–25, Nov 30–Dec 4",
    location: "Dubai, UAE",
    destination: "Dubai",
  }),

  // LONDON – UK (4 Programmes)
  makeProgramme({
    slug: "london-building-capacity-executives-utility-regulators",
    title: "Building Capacity For Executives and Top Management Utility Regulators",
    category: "London Hub",
    programmeType: "Foreign",
    fee: "£4,800 GBP",
    currency: "GBP",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "July 6–10",
    location: "London, UK",
    destination: "London",
  }),
  makeProgramme({
    slug: "london-next-generation-challenges-telecom-executives",
    title: "Next Generation Challenges & Opportunities for Telecom Senior Executives",
    category: "London Hub",
    programmeType: "Foreign",
    fee: "£4,800 GBP",
    currency: "GBP",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Aug 17–21",
    location: "London, UK",
    destination: "London",
  }),
  makeProgramme({
    slug: "london-capacity-building-ict-literacy-security",
    title: "Capacity Building Workshop on ICT Literacy and Security Awareness",
    category: "London Hub",
    programmeType: "Foreign",
    fee: "£4,800 GBP",
    currency: "GBP",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Sept 21–25",
    location: "London, UK",
    destination: "London",
  }),
  makeProgramme({
    slug: "london-infusing-knowledge-management-public-private",
    title: "Infusing Knowledge Management in Public Service and Private Sector",
    category: "London Hub",
    programmeType: "Foreign",
    fee: "£4,800 GBP",
    currency: "GBP",
    feeAmount: 4800,
    target: "Middle/Senior Management",
    schedule: "Oct 19–23",
    location: "London, UK",
    destination: "London",
  }),

  // HOUSTON – TEXAS, USA (5 Programmes)
  makeProgramme({
    slug: "houston-capacity-building-ict-literacy-innovations",
    title: "Capacity Building Workshop on ICT Literacy, New Innovations and Security Awareness",
    category: "Houston Hub",
    programmeType: "Foreign",
    fee: "$5,000 USD",
    currency: "USD",
    feeAmount: 5000,
    target: "Middle/Senior Management",
    schedule: "June 22–26",
    location: "Houston, Texas, USA",
    destination: "Houston",
  }),
  makeProgramme({
    slug: "houston-managing-emerging-concepts-smart-cities-big-data-ai",
    title: "Strategies for Managing Emerging Concepts of Smart Cities Big Data, AI, EI and 5G: Prospects and Challenges",
    category: "Houston Hub",
    programmeType: "Foreign",
    fee: "$5,000 USD",
    currency: "USD",
    feeAmount: 5000,
    target: "Middle/Senior Management",
    schedule: "July 20–24",
    location: "Houston, Texas, USA",
    destination: "Houston",
  }),
  makeProgramme({
    slug: "houston-infusing-knowledge-management-public-private",
    title: "Infusing Knowledge Management in Public Service and Private Sector For Improved Productivity",
    category: "Houston Hub",
    programmeType: "Foreign",
    fee: "$5,000 USD (1wk) / $9,500 USD (2wks)",
    currency: "USD",
    feeAmount: 5000,
    target: "Middle/Senior Management",
    schedule: "August 10–14 (1wk) / Aug 10–21 (2wks)",
    location: "Houston, Texas, USA",
    destination: "Houston",
    duration: "1 Week or 2 Weeks",
  }),
  makeProgramme({
    slug: "houston-next-generation-challenges-telecom-utilities",
    title: "Next Generation Challenges & Opportunities for Telecom & Other Utilities Regulatory Managers",
    category: "Houston Hub",
    programmeType: "Foreign",
    fee: "$5,000 USD (1wk) / $9,500 USD (2wks)",
    currency: "USD",
    feeAmount: 5000,
    target: "Middle/Senior Management",
    schedule: "Oct 12–16 (1wk) / Oct 12–23 (2wks)",
    location: "Houston, Texas, USA",
    destination: "Houston",
    duration: "1 Week or 2 Weeks",
  }),
  makeProgramme({
    slug: "houston-capacity-building-ict-literacy-and-security",
    title: "Capacity Building Workshop on ICT Literacy and Security Awareness",
    category: "Houston Hub",
    programmeType: "Foreign",
    fee: "$9,500 USD",
    currency: "USD",
    feeAmount: 9500,
    target: "Middle/Senior Management",
    schedule: "Nov 9–13 (1wk) / Nov 9–20 (2wks)",
    location: "Houston, Texas, USA",
    destination: "Houston",
    duration: "2 Weeks",
  }),
];

export const PROGRAMMES: Programme[] = [...LOCAL_PROGRAMMES, ...FOREIGN_PROGRAMMES];

export const PROGRAM_CATEGORIES = [
  "All",
  "Local/Open",
  "Foreign",
  "Accounting & Financial Management",
  "General Administration & Management",
  "Telecom & Utilities Regulation",
  "Consumer Protection & Engagement",
  "Environmental Sustainability & Management",
  "Oil & Gas Sector",
  "Secretarial Administration & Management",
  "Capital Market & Securities",
  "Information Technology",
  "Legal & Legislative",
  "Power & Energy Sector",
  "Maritime & Transportation",
  "Pension Management",
  "Special Training Programmes",
];

export function getProgramme(slug: string) {
  return PROGRAMMES.find((p) => p.slug === slug);
}

export function relatedProgrammes(slug: string, count = 3) {
  const current = getProgramme(slug);
  if (!current) return PROGRAMMES.slice(0, count);
  return PROGRAMMES.filter((p) => p.slug !== slug)
    .sort(
      (a, b) =>
        Number(b.category === current.category) -
        Number(a.category === current.category)
    )
    .slice(0, count);
}

/* ---------------- Research & insights ---------------- */

export const RESEARCH_THEMES = [
  {
    title: "Leadership & Institutions",
    blurb: "How durable institutions are built, led and renewed.",
  },
  {
    title: "Markets & the Global Africa",
    blurb: "Capital, enterprise and development across African markets.",
  },
  {
    title: "Enterprise, Innovation & Scale",
    blurb: "Founding, financing and scaling ventures under conditions of real uncertainty.",
  },
  {
    title: "Organizations & the Future of Work",
    blurb: "How organizations decide, develop people and reorganize.",
  },
];

export const INSIGHT_TYPES = [
  "All",
  "Research",
  "Leadership Perspective",
  "Case Study",
  "Events",
];

export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "quote"; text: string };

export type Article = {
  slug: string;
  category: string;
  kicker: string;
  title: string;
  dek: string;
  image: string;
  alt: string;
  status: "Forthcoming";
  blocks: ArticleBlock[];
  related: string[];
};

export const ARTICLES: Article[] = [
  {
    slug: "quiet-authority-of-long-term-institutions",
    category: "Leadership & Institutions",
    kicker: "Flagship essay",
    title: "The quiet authority of long-term institutions",
    dek: "Why the organizations that shape centuries rarely optimize for the loudest quarter — and what that asks of their leaders.",
    image: IMAGES.books,
    alt: "Hardbound research volumes arranged by hand in warm library light",
    status: "Forthcoming",
    blocks: [
      {
        type: "p",
        text: "There is a particular quality of authority that does not announce itself. It belongs to institutions that expect to exist in a hundred years, and make decisions accordingly. Their leaders are not uninterested in results; they are interested in a different order of result.",
      },
      {
        type: "p",
        text: "This essay, the opening statement of the GIBS journal, argues that management education has drifted toward the temporality of the quarter and the feed, and that a serious school must deliberately teach the long view: compounding reputation, inherited trust, institutions that outlive their founders.",
      },
      { type: "h2", text: "The long view as a discipline" },
      {
        type: "p",
        text: "Long-termism is not patience as a temperament. It is a discipline of decisions about capital, people, quality and silence, one that can be taught, rehearsed and measured. It depends on leaders who can hold two horizons at once: the urgent institution in front of them and the distant one they are answerable to.",
      },
      {
        type: "quote",
        text: "Authority, quietly held, is the freedom to make the decision that only looks correct in twenty years.",
      },
      { type: "h2", text: "What the journal will examine" },
      {
        type: "p",
        text: "The published essay will draw on institutional history, governance practice and the experience of founders building for permanence across the Global Africa. It will avoid the consolations of rankings and the noise of the news cycle, and ask instead what institutions require of the people entrusted with them.",
      },
    ],
    related: ["changed-decisions", "growth-mapped-from-the-continent"],
  },
  {
    slug: "growth-mapped-from-the-continent",
    category: "Markets & the Global Africa",
    kicker: "Research preview",
    title: "The next decade of growth, mapped from the continent",
    dek: "The demographic, capital and infrastructure shifts rewriting the investment map, seen from the markets themselves.",
    image: IMAGES.city,
    alt: "The GIBS campus at golden hour, sandstone pavilions and open sky",
    status: "Forthcoming",
    blocks: [
      {
        type: "p",
        text: "Most maps of the next global economy are still drawn elsewhere. This research preview sets out the questions GIBS faculty will pursue with investors, operators and officials inside the markets the maps describe.",
      },
      { type: "h2", text: "Three shifts worth studying closely" },
      {
        type: "p",
        text: "The first is the restructuring of capital: the slow rise of patient, institutional and domestic capital alongside external flows. The second is infrastructure as strategy, where logistics and energy reshape what is possible for enterprise. The third is demography, not as a dividend assumed but as an obligation to be met through education and employment at scale.",
      },
      {
        type: "quote",
        text: "A market mapped from outside is a forecast. Mapped from inside, it becomes a plan.",
      },
      {
        type: "p",
        text: "The full research piece will be published as the underlying fieldwork and case material are completed. Figures, where cited, will carry sources and dates.",
      },
    ],
    related: ["quiet-authority-of-long-term-institutions", "changed-decisions"],
  },
  {
    slug: "changed-decisions",
    category: "Enterprise, Innovation & Scale",
    kicker: "Leadership perspective",
    title: "Executive education, measured in changed decisions",
    dek: "How to judge a leadership programme: not by decks completed, but by decisions made differently afterwards.",
    image: IMAGES.seminar,
    alt: "Sunlight through the sandstone colonnade of the GIBS campus",
    status: "Forthcoming",
    blocks: [
      {
        type: "p",
        text: "Most executive education is evaluated at the wrong moment. The satisfaction survey closes while the lessons are still warm; the true test arrives weeks later, in a meeting where a leader must decide under pressure.",
      },
      { type: "h2", text: "A harder, fairer measure" },
      {
        type: "p",
        text: "GIBS proposes a simple shift in perspective: a programme succeeds when it changes a specific decision the participant would otherwise have made, such as a hire, an allocation, or a conversation avoided or held. That standard changes how a programme is designed before it changes how it is measured.",
      },
      {
        type: "p",
        text: "The perspective will be developed alongside the organizations that commission custom work, with honest accounts of failure included. It will be published in the first edition of the journal.",
      },
    ],
    related: ["quiet-authority-of-long-term-institutions", "growth-mapped-from-the-continent"],
  },
];

export function getArticle(slug: string) {
  return ARTICLES.find((a) => a.slug === slug);
}

export function relatedArticles(slug: string, count = 2) {
  const current = getArticle(slug);
  if (!current) return ARTICLES.slice(0, count);
  return current.related
    .map((s) => ARTICLES.find((a) => a.slug === s))
    .filter((a): a is Article => Boolean(a))
    .slice(0, count);
}

/* ---------------- Admissions ---------------- */

export const ADMISSIONS_STEPS = [
  {
    n: "01",
    title: "Discover",
    body: "Explore our 135 local and international training programmes, attend an open conversation, or ask the Concierge.",
  },
  {
    n: "02",
    title: "Choose",
    body: "Select the specific course and location that fits your organizational or professional trajectory.",
  },
  {
    n: "03",
    title: "Prepare",
    body: "Assemble your nomination details, staff list, and organizational sponsorship authorization.",
  },
  {
    n: "04",
    title: "Apply / Register",
    body: "Submit registration through the official portal or contact admissions directly.",
  },
  {
    n: "05",
    title: "Confirmation",
    body: "Receive official confirmation, schedule details, and venue instructions from the registrar.",
  },
  {
    n: "06",
    title: "Attend",
    body: "Join your cohort at Ilorin HQ, Abuja, Ibafo, or overseas international hubs.",
  },
];

export const REQUIREMENTS_ACCORDION = [
  {
    q: "Participant nomination & target audience",
    a: "Each programme specifies target participant levels (e.g., Senior & Middle Management, Board Members, Executive Directors, or All Staff).",
  },
  {
    q: "Sponsorship & billing",
    a: "Public Sector (MDAs) and Private Sector organizations may sponsor individual participants or cohorts. Invoices and compliance documents are issued upon request.",
  },
  {
    q: "Certifications",
    a: "Participants receive official GIBS Certificates of Completion accredited by CMD, ITF, and NSTIF.",
  },
];

export const HOME_PROGRAMME_BANDS: {
  band: string;
  note: string;
  slugs: string[];
}[] = [
  {
    band: "Local / Open Training",
    note: "113 specialized executive and management courses across Nigeria",
    slugs: [
      "public-sector-accounting-procedure-and-standards",
      "a-modern-approach-to-procurement-strategic-perspective",
      "ethical-standards-and-organisational-development",
      "regulatory-and-operational-strategies-for-telecom-executives",
    ],
  },
  {
    band: "Overseas International Training",
    note: "22 foreign programmes across Kigali, Dubai, London, and Houston",
    slugs: [
      "kigali-managing-service-quality-and-customer-satisfaction",
      "dubai-developing-management-skills-for-administrators",
      "london-building-capacity-executives-utility-regulators",
      "houston-capacity-building-ict-literacy-innovations",
    ],
  },
];

export const ADMISSIONS_FAQS = [
  {
    q: "How do I register for a GIBS training programme?",
    a: "You can register online through the website, email gibsilorin@gmail.com / goshenibs22@gmail.com, or call our phone lines.",
  },
  {
    q: "Where are the training venues?",
    a: "Local courses hold at GIBS Ilorin HQ, Abuja Center, Ibafo (Ogun) Center, Lagos, Keffi, etc. Foreign courses hold in Kigali, Dubai, London, and Houston.",
  },
  {
    q: "Are GIBS programmes accredited?",
    a: "Yes. GIBS is registered under CAC RC 1178333 and accredited by CMD, ITF (Certificate of Compliance), and NSTIF, with technical partnership with Pacific Institute of Technology, Georgia, USA.",
  },
];

export const CAMPUS_FACILITIES = [
  { name: "Ilorin HQ Lecture Rooms", note: "12 air-conditioned lecture halls & 100-person hall" },
  { name: "Library & Research Center", note: "Comprehensive management literature & digital resources" },
  { name: "Abuja Training Center", note: "2 large halls, 7 lecture rooms, syndicate rooms in FHA Lugbe" },
  { name: "Ibafo Training Center", note: "Lecture rooms & syndicate rooms along Lagos-Ibadan Express Road" },
  { name: "Guest Accommodation", note: "20-room guest facility at Ilorin HQ & guest units in Abuja" },
  { name: "Recreation & Sports Grounds", note: "Olympic lawn tennis court, international table tennis, keep-fit grounds" },
];

export const ENQUIRY_TYPES = [
  "Local / Open Training Programmes (113 courses)",
  "Overseas / Foreign Training (Kigali, Dubai, London, Houston)",
  "Custom Training for Organizations / MDAs",
  "Campus Facilities & Guest House Booking",
  "Media, Accreditation & Partnerships",
  "General Information",
];

export const STATIC_PAGES = [
  { title: "Programmes", to: "/programmes", blurb: "Complete 135 local and foreign training programme catalogue.", type: "Page" },
  { title: "Executive Education", to: "/executive-education", blurb: "Executive training, custom corporate solutions, and international hubs.", type: "Page" },
  { title: "Admissions", to: "/admissions", blurb: "Programme registration, schedules, fees, and enrolment guidance.", type: "Page" },
  { title: "About GIBS", to: "/about", blurb: "Institutional history, CAC registration, vision, mission, and leadership.", type: "Page" },
  { title: "Faculty & Research", to: "/faculty", blurb: "14 academic board advisor designations and research areas.", type: "Page" },
  { title: "Campus", to: "/campus", blurb: "Ilorin HQ, Abuja, and Ibafo campus locations and facilities.", type: "Page" },
  { title: "Contact", to: "/contact", blurb: "Reach GIBS via email, phones, postal address, or enquiry form.", type: "Page" },
];
`;

fs.writeFileSync('src/lib/data.ts', dataContent);
console.log('src/lib/data.ts updated successfully');
