#!/usr/bin/env python3
"""Shared extraction and canonicalisation for the GIBS programme catalogue.

This module is the single place that knows how to turn the current source of
truth into a form the database schema can hold. Everything else
(`export_snapshot.py`, `programmes_to_sql.py`, `../qa/parity_check.py`) uses it,
so the snapshot, the SQL and the parity checks can never disagree about what the
source means.

SOURCE OF TRUTH
    src/lib/data.ts, the `PROGRAMMES` array. That file is GENERATED by
    scripts/generate_data_ts.py. This module does not modify it.

SCOPE / SAFETY
    Read-only with respect to the repository. Contains no database connection
    and no credentials. Stdlib only.

FIELD CLASSIFICATION (the migration contract)
    PRESERVED SOURCE   id, code, num, slug, title, category, destination,
                       target_audience, schedule_text, duration_label,
                       fee (+ tier), currency, fee_notes
    DERIVED            tagline, summary, format, audience,
                       indicative_structure, outcomes, faqs, in_plant_available
    OMITTED            startDate  (verified byte-identical to schedule)
                       officialOnly (empty array on all 135 records)
                       fees       (formatted display string; regenerated)
                       requirements (generated but rendered by no live page;
                                     retained inside `legacy` only)
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
DATA_TS = REPO / "src" / "lib" / "data.ts"
SNAPSHOT = REPO / "db" / "legacy" / "programmes.snapshot.json"

# Same scoped-regex approach the existing scripts/validate_current_data.py uses:
# everything outside the array literal is hand-written TypeScript.
_PROGRAMMES_RE = re.compile(
    r"export const PROGRAMMES: Programme\[\] = (\[.*?\n\]);", re.S
)

CURRENCIES = ("NGN", "USD", "GBP")

# Order mirrors the TypeScript union in src/types/data.ts.
CATEGORY_ORDER = (
    "Accounting and Financial Management",
    "General Administration and Management",
    "Telecom & Utilities Regulation",
    "Consumer Protection & Utilities",
    "Environmental Sustainability & Management",
    "Oil & Gas Sector",
    "Secretarial Administration & Management",
    "Capital Market & Securities Management",
    "Information Technology Workshops",
    "Legal & Legislative Studies",
    "Power & Energy Sector",
    "Maritime & Transportation",
    "Pension Management",
    "Special Executive Training",
    "Foreign Executive Training",
)

# Order mirrors FOREIGN_DESTINATIONS plus Local, which is a real destination in
# the source (not a NULL).
DESTINATION_ORDER = (
    ("Local", "NGN", True),
    ("Kigali", "USD", False),
    ("Dubai", "USD", False),
    ("London", "GBP", False),
    ("Houston", "USD", False),
)

REQUIRED_FIELDS = (
    "id", "code", "num", "slug", "title", "category", "destination",
    "fee", "currency", "targetAudience", "schedule", "duration",
    "inPlantAvailable", "tagline", "summary", "format", "audience",
    "indicativeStructure", "outcomes", "faqs",
)


class SourceError(RuntimeError):
    """Raised when the source data is not what the contract expects."""


def read_data_ts() -> str:
    if not DATA_TS.exists():
        raise SourceError(f"source file not found: {DATA_TS}")
    return DATA_TS.read_text(encoding="utf-8")


def source_sha256() -> str:
    return hashlib.sha256(read_data_ts().encode("utf-8")).hexdigest()


def load_source_programmes() -> list[dict]:
    """Extract and validate the PROGRAMMES array from src/lib/data.ts."""
    text = read_data_ts()
    match = _PROGRAMMES_RE.search(text)
    if not match:
        raise SourceError(
            "could not locate the PROGRAMMES array in src/lib/data.ts; "
            "the generator template may have changed shape"
        )
    try:
        programmes = json.loads(match.group(1))
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive
        raise SourceError(f"PROGRAMMES array is not valid JSON: {exc}") from exc
    if not isinstance(programmes, list):
        raise SourceError("PROGRAMMES did not parse to a list")

    seen_id: set[str] = set()
    seen_code: set[str] = set()
    seen_slug: set[str] = set()
    seen_num: set[int] = set()

    for index, p in enumerate(programmes):
        where = f"record #{index} ({p.get('id', '<no id>')})"
        missing = [f for f in REQUIRED_FIELDS if f not in p]
        if missing:
            raise SourceError(f"{where}: missing required field(s) {missing}")
        for field, seen in (("id", seen_id), ("code", seen_code),
                            ("slug", seen_slug), ("num", seen_num)):
            value = p[field]
            if value in seen:
                raise SourceError(f"{where}: duplicate {field} {value!r}")
            seen.add(value)
        if not isinstance(p["num"], int):
            raise SourceError(f"{where}: num must be an integer")
        if p["category"] not in CATEGORY_ORDER:
            raise SourceError(f"{where}: unknown category {p['category']!r}")
        if p["destination"] not in {d[0] for d in DESTINATION_ORDER}:
            raise SourceError(f"{where}: unknown destination {p['destination']!r}")
        if p["currency"] not in CURRENCIES:
            raise SourceError(f"{where}: unknown currency {p['currency']!r}")
        if not isinstance(p["fee"], (int, float)):
            raise SourceError(f"{where}: fee must be numeric")
        secondary = p.get("feeSecondary")
        if secondary is not None and not isinstance(secondary, (int, float)):
            raise SourceError(f"{where}: feeSecondary must be numeric or absent")

    return programmes


def build_canonical_rows(programmes: list[dict]) -> dict:
    """Turn source records into schema-shaped rows.

    Returns a dict with `categories`, `destinations`, `programmes` and the
    expected invariants, ready for SQL emission or comparison.
    """
    categories = [{"name": name, "sort_order": i + 1}
                  for i, name in enumerate(CATEGORY_ORDER)]
    destinations = [{"name": name, "default_currency": cur,
                     "is_local": local, "sort_order": i + 1}
                    for i, (name, cur, local) in enumerate(DESTINATION_ORDER)]
    cat_id = {c["name"]: i + 1 for i, c in enumerate(categories)}
    dest_id = {d["name"]: i + 1 for i, d in enumerate(destinations)}

    rows = []
    for p in programmes:
        fees = [{"amount": p["fee"], "currency": p["currency"], "tier": 1,
                 "label": None}]
        secondary = p.get("feeSecondary")
        if secondary is not None:
            fees.append({"amount": secondary, "currency": p["currency"],
                         "tier": 2, "label": None})

        rows.append({
            "id": p["id"],
            "code": p["code"],
            "num": p["num"],
            "slug": p["slug"],
            "title": p["title"],
            "category_id": cat_id[p["category"]],
            "category": p["category"],
            "destination_id": dest_id[p["destination"]],
            "destination": p["destination"],
            "target_audience": p["targetAudience"],
            "schedule_text": p["schedule"],
            "duration_label": p["duration"],
            "in_plant_available": bool(p["inPlantAvailable"]),
            "fee_notes": p.get("feeNotes"),
            "fees": fees,
            "tagline": p["tagline"],
            "summary": p["summary"],
            "format": p.get("format"),
            "audience": p["audience"],
            "indicative_structure": p["indicativeStructure"],
            "outcomes": p["outcomes"],
            "faqs": p["faqs"],
            "legacy": p,
        })

    return {"categories": categories, "destinations": destinations,
            "programmes": rows}


def sql_literal(value) -> str:
    """Render a Python value as a PostgreSQL literal.

    Single-quoted standard strings only, with embedded quotes doubled. This is
    safe under the default `standard_conforming_strings = on` because backslashes
    are then not escape characters. No E'' strings and no dollar quoting, so the
    emitted SQL cannot be terminated early by hostile data.
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, ensure_ascii=False, sort_keys=True,
                           separators=(",", ":"))
    text = str(value)
    if "\\" in text:
        raise SourceError(
            "refusing to emit a value containing a backslash: the generated "
            "SQL must not depend on server GUC settings to be read correctly"
        )
    return "'" + text.replace("'", "''") + "'"


def render_sql_header(snapshot: dict) -> str:
    """Deterministic provenance header for the generated seed SQL."""
    return "\n".join([
        "-- GENERATED FILE — DO NOT HAND-EDIT.",
        "-- Regenerate with:",
        "--   python3 scripts/import/programmes_to_sql.py "
        "--out db/schema/002_programme_seed.sql",
        "--",
        f"-- Source of truth : {snapshot['generated_from']}",
        f"-- Source sha256   : {snapshot['source_sha256']}",
        f"-- Records         : {snapshot['record_count']}",
        "-- Re-running the generator on unchanged input reproduces this file",
        "-- byte for byte, so any diff here is a real change to the catalogue.",
        "",
    ])


def expected_display_fee(row: dict) -> str:
    """Recreate the source `fees` display string from the tiered fee rows.

    Verified against the source for 133 of 135 records. The 2 exceptions are the
    Houston records whose `fees` is overridden by `feeNotes`; callers must
    handle those via `fee_notes`.
    """
    symbol = {"NGN": "₦", "USD": "$", "GBP": "£"}[row["fees"][0]["currency"]]
    amount = row["fees"][0]["amount"]
    formatted = f"{symbol}{int(amount):,}"
    if row["fees"][0]["currency"] == "NGN":
        return formatted
    return f"{formatted} {row['fees'][0]['currency']}"


def build_snapshot(programmes: list[dict]) -> dict:
    """The committed migration artifact: source records plus provenance."""
    return {
        "snapshot_version": 1,
        "artifact_notice": (
            "MIGRATION ARTIFACT — DERIVED, NOT CANONICAL. This file is a "
            "verbatim export of the PROGRAMMES array in src/lib/data.ts, which "
            "remains the source of truth. Do not hand-edit: regenerate with "
            "`python3 scripts/import/export_snapshot.py`. If this file and "
            "src/lib/data.ts disagree, src/lib/data.ts wins and the snapshot is "
            "stale."
        ),
        "generated_from": "src/lib/data.ts",
        "source_sha256": source_sha256(),
        "record_count": len(programmes),
        "programmes": programmes,
    }


def load_snapshot() -> dict:
    if not SNAPSHOT.exists():
        raise SourceError(
            f"snapshot not found: {SNAPSHOT}\n"
            "run: python3 scripts/import/export_snapshot.py"
        )
    return json.loads(SNAPSHOT.read_text(encoding="utf-8"))